import type { Metadata } from "next";
import Chart, {
  Chart as Chartjs,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler,
} from "chart.js/auto";
import { Line, Bar, Scatter, Bubble } from "react-chartjs-2";

export const metadata: Metadata = {
  title: "RIS",
  description: "Generated by create next app",
};
const data = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      label: "Dataset 1",
      data: [65, 59, 80, 81, 56, 55, 40],
      fill: false,
      backgroundColor: "rgb(255, 99, 132)",
      borderColor: "rgba(255, 99, 132, 0.2)",
    },
    {
      label: "Dataset 2",
      data: [28, 48, 40, 19, 86, 27, 90],
      fill: false,
      backgroundColor: "rgb(53, 162, 235)",
      borderColor: "rgba(53, 162, 235, 0.2)",
    },
  ],
};

const options = {
  Plugins: {
    legend: {
      display: false,
    },
    elements: {
      Line: {
        tension: 0.4,
        borderWidth: 2,
        borderColor: "rgb(47,97,68,1)",
        fill: "start",
        backgroundColor: "rgb(47,97,68,1)",
      },
      point: {
        radius: 0,
        hitRadius: 10,
      },
    },
  },
  scales: {
    xAxis: {
      display: false,
    },
    yAxis: {
      display: false,
    },
  },
};
Chartjs.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
);
export default function Chartdaw() {
  return (
    <div>
      <Line data={data} options={options} />
    </div>
  );
}
