import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "RIS",
  description: "Generated by create next app",
};

export default function RIS() {
  return (
    <div className="container h-screen py-2 bg-gray-300  mx-auto">
      <div className="text-center">
        <p className="font-medium px-4 rounded-[15px]">
          <span> NEGROS ORIENTAL STATE UNIVERSITY</span>
        </p>
        <p className="font-medium px-4 rounded-[15px]">
          <span> Main Campus I, Dumaguete </span>
        </p>
        <p className="text-xl pt-4 px-4 rounded-[15px]">
          <span> REQUISITION AND ISSUE SLIP </span>
        </p>
        <p className="font-medium px-4 rounded-[15px]">
          <span> (for on stock common supplies and equipment) </span>
        </p>
      </div>
      <div className="container py-2 mx-auto">
        <div className=" items-center px-4 justify-center"></div>
      </div>
    </div>
  );
}
