import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Requests",
  description: "Generated by create next app",
};

export default function Request() {
  return (
    <div className="md:w-54 lg:w-full  h-full pt-2 bg-gray-300    flex flex-col place-items-center">
      <div className="  grid grid-cols-2 h-16  ">
        <div className="  px-2 rounded-[55px] h-[62px]">
          <div className="  px-2 text-2xl   rounded-[50px]">
            <div className="font-extrabold">Request and Returns</div>
            <p className="font-normal text-sm ">Main Office</p>
          </div>
        </div>
        <div className=" pl-[55%] px-4 rounded-[55px] ">
          <div className=" px-2 text-sm text-left columns-2 bg-white  rounded-[55px] h-[62px] w-[220px]">
            <div className="place-items-center  ">
              <img
                className="avatar mt-1"
                src="https://images.unsplash.com/photo-1682407186023-12c70a4a35e0?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=2832&amp;q=80"
                alt="nature image"
              />
              <div className="font-extrabold">
                Adrian cardosa<p className="font-normal text-sm ">student</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className=" py-4  w-[97%]">
        <div className="grid bg-white w-full  text-gray-900 px-4 rounded-t-[15px]   py-4 grid-cols-5 gap-20  ">
          <div className="flex w-full pt-2 gap-2 shrink-0 md:w-max">
            <div className="w-full md:w-72">
              <div className="relative   h-10 w-full min-w-[200px]">
                <div className="absolute grid  w-5 h-5 top-2/4 right-3 -translate-y-2/4 place-items-center text-blue-gray-500">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    aria-hidden="true"
                    className="w-5 h-5 "
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"
                    ></path>
                  </svg>
                </div>
                <input
                  className="peer h-full  w-full rounded-[7px] border border-blue-gray-200 border-t-transparent  bg-gray-300 px-3 py-2.5 !pr-9 font-sans text-sm font-normal text-blue-gray-700 outline outline-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200 focus:border-2 focus:border-gray-200 focus:border-t-transparent focus:outline-0 disabled:border-0 disabled:bg-blue-gray-50"
                  placeholder=" "
                />
                <label className="before:content[' '] after:content[' '] pointer-events-none absolute left-0 -top-1.5 flex h-full w-full select-none !overflow-visible truncate text-[11px] font-normal leading-tight text-gray-500 transition-all before:pointer-events-none before:mt-[6.5px] before:mr-1 before:box-border before:block before:h-1.5 before:w-2.5 before:rounded-tl-md before:border-t before:border-l before:border-blue-gray-200 before:transition-all after:pointer-events-none after:mt-[6.5px] after:ml-1 after:box-border after:block after:h-1.5 after:w-2.5 after:flex-grow after:rounded-tr-md after:border-t after:border-r after:border-blue-gray-200 after:transition-all peer-placeholder-shown:text-sm peer-placeholder-shown:leading-[3.75] peer-placeholder-shown:text-blue-gray-500 peer-placeholder-shown:before:border-transparent peer-placeholder-shown:after:border-transparent peer-focus:text-[11px] peer-focus:leading-tight peer-focus:text-gray-900 peer-focus:before:border-t-2 peer-focus:before:border-l-2 peer-focus:before:!border-gray-200 peer-focus:after:border-t-2 peer-focus:after:border-r-2 peer-focus:after:!border-gray-200 peer-disabled:text-transparent peer-disabled:before:border-transparent peer-disabled:after:border-transparent peer-disabled:peer-placeholder-shown:text-blue-gray-500">
                  Search
                </label>
              </div>
            </div>

            <div className="py">
              <div className="dropdown inline-block relative">
                <button className="bg-gray-300 text-gray-700 font-normal py-2 px-4 rounded inline-flex items-center">
                  <span className="mr-1">Dropdown</span>
                  <svg
                    className="fill-current h-4 w-4"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                  >
                    <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />{" "}
                  </svg>
                </button>
                <ul className="dropdown-menu absolute hidden text-gray-700 pt-1">
                  <li className="">
                    <a
                      className="rounded-t bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap"
                      href="#"
                    >
                      One
                    </a>
                  </li>
                  <li className="">
                    <a
                      className="bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap"
                      href="#"
                    >
                      Two
                    </a>
                  </li>
                  <li className="">
                    <a
                      className="rounded-b bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap"
                      href="#"
                    >
                      Three is the magic number
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div className="">
              <div className="dropdown inline-block relative">
                <button className="bg-gray-300 text-gray-700 font-normal py-2 px-4 rounded inline-flex items-center">
                  <span className="mr-1">Pending</span>
                  <svg
                    className="fill-current h-4 w-4"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                  >
                    <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />{" "}
                  </svg>
                </button>
                <ul className="dropdown-menu absolute hidden text-gray-700 pt-1">
                  <li className="">
                    <a
                      className="rounded-t bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap"
                      href="#"
                    >
                      One
                    </a>
                  </li>
                  <li className="">
                    <a
                      className="bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap"
                      href="#"
                    >
                      Two
                    </a>
                  </li>
                  <li className="">
                    <a
                      className="rounded-b bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap"
                      href="#"
                    >
                      Three is the magic number
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col h-[350px] bg-white  ">
          <div className="">
            <table className="w-full text-left table-auto min-w-max">
              <thead>
                <tr>
                  <th className="p-4 bg-blue-gray-50/50">
                    <p className="block font-sans text-lg  antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                      Item ID
                    </p>
                  </th>
                  <th className="p-4 border-blue-gray-100 bg-blue-gray-50/50">
                    <p className="block font-sans text-lg  antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                      Name of Item
                    </p>
                  </th>
                  <th className="p-4  border-blue-gray-100 bg-blue-gray-50/50">
                    <p className="block font-sans text-lg  antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                      Unit of Measure
                    </p>
                  </th>
                  <th className="p-4  border-blue-gray-100 bg-blue-gray-50/50">
                    <p className="block font-sans text-lg  antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                      Quantity
                    </p>
                  </th>
                  <th className="p-4  border-blue-gray-100 bg-blue-gray-50/50">
                    <p className="block font-sans text-lg  antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                      Last Updated
                    </p>
                  </th>
                  <th className="p-4  border-blue-gray-100 bg-blue-gray-50/50">
                    <p className="block font-sans text-lg  antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                      Action
                    </p>
                  </th>
                </tr>
              </thead>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
