import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Requests",
  description: "Generated by create next app",
};

export default function Request() {
  return (
    <div className="max-w-full  max-h-full w-full h-full pt-4 bg-gray-300   flex flex-col place-items-center">
      <div className="w-[97%] h-16 text-2xl font-extrabold   flex-col ">
        <div>
          <p className="pt-2 px-2 rounded-[50px]"> Dashboard</p>
        </div>
      </div>

      <div className="h-full py-2  px-2 w-full">
        <div className=" items-center px-4 justify-center">
          <div className="grid grid-cols-1 ">
            <div className="relative  h-[281px] bg-white py-4 px-4 rounded-3xl my-4 ">
              <div className="justify-between flex">
                <p> Stocks</p>
                <div className="">view all</div>
              </div>

              <div>
                <table className="table-fixed w-full ">
                  <thead>
                    <tr>
                      <th>Item ID</th>
                      <th> Name of Item</th>
                      <th>Unit of Measure</th>
                      <th>Quantity</th>
                      <th>Last Updated</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>123</td>
                      <td>pentelpen</td>
                      <td>pcs</td>
                      <td>2</td>
                      <td>2-2-2022</td>
                      <td>edit</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
