import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Activity Logs",
  description: "Generated by create next app",
};

export default function Queue() {
  return (
    <div className="w-full h-full pt-3 flex flex-col justify-center place-items-center">
      <div className="w-[97%] h-16 text-2xl font-extrabold flex flex-col ">
        <div className=" bg-gray-500 w-50%">
          <p className="py-2 px-2 rounded-[50px]">Welcome to Activity Logs.</p>
        </div>
      </div>
      <div className="h-[90%] py- px-2 bg-gray-500 w-[97%]">
        <p className=" py-2 px-2"></p>
      </div>
    </div>
  );
}
