import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/layout/side-bar/sidebar";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import TopBar from "@/components/layout/top-bar/page";

const montserrat = Montserrat({
  subsets: ["cyrillic"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-montserrat", montserrat.variable)}>
        <div className="w-full h-screen flex">
          <Sidebar />
          <div className="w-full h-full flex flex-col">
            <TopBar />
            {children}
          </div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
